import React , { Component } from 'react'

export const breadcrumbconfig = {
  getBreadcrumbUrl() {
    const breadcrumbUrl = [
      {
          "key": "user",
          "path": "/user",
          "name": "用户管理",
          "catalog": "0",
          "params": []
      }, {
          "key": "lists",
          "path": "/user/lists",
          "name": "用户列表",
          "catalog": "1",
          "params": []
        }, {
          "key": "detail",
          "path": "/user/list/detail",
          "name": "用户详情",
          "catalog": "2",
          "params": []
      }, {
          "key": "job",
          "path": "/job",
          "name": "任务来源渠道管理",
          "catalog": "0",
          "params": []
      }, {
          "key": "channel",
          "path": "/job/channel",
          "name": "渠道列表",
          "catalog": "1",
          "params": []
      }, {
        "key": "basicinfo",
        "path": "/job/list/basicinfo",
        "name": "基本信息",
        "catalog": "2",
        "params": []
      }, {
        "key": "extend",
        "path": "/extend",
        "name": "用户推广渠道管理",
        "catalog": "0",
        "params": []
      }, {
        "key": "extendlists",
        "path": "/extend/extendlists",
        "name": "推广渠道列表",
        "catalog": "1",
        "params": []
      }, {
        "key": "extenddetail",
        "path": "/extend/extendlist/extenddetail",
        "name": "推广渠道详情",
        "catalog": "2",
        "params": []
      }, {
        "key": "workorder",
        "path": "/workorder",
        "name": "任务工单管理管理",
        "catalog": "0",
        "params": []
      }, {
        "key": "workordermanage",
        "path": "/workorder/manage",
        "name": "工单管理",
        "catalog": "1",
        "params": []
      }, {
        "key": "channelcommission",
        "path": "/channelcommission",
        "name": "用户推广渠道佣金列表",
        "catalog": "0",
        "params": []
      }, {
        "key": "commissionlists",
        "path": "/channelcommission/commissionlists",
        "name": "佣金列表",
        "catalog": "1",
        "params": []
      }, {
        "key": "comissiondetail",
        "path": "/channelcommission/commissionlist/comissiondetail",
        "name": "佣金详情",
        "catalog": "2",
        "params": []
      }, {
        "key": "cashout",
        "path": "/cashout",
        "name": "佣金发放",
        "catalog": "0",
        "params": []
      }, {
        "key": "cashoutlists",
        "path": "/cashout/cashoutlists",
        "name": "提现列表",
        "catalog": "1",
        "params": []
      }, {
        "key": "auditedcashoutlists",
        "path": "/cashout/auditedcashoutlists",
        "name": "提现已审核列表",
        "catalog": "1",
        "params": []
      }, {
        "key": "rejectcashoutlists",
        "path": "/cashout/rejectcashoutlists",
        "name": "提现已拒绝列表",
        "catalog": "1",
        "params": []
      }, {
        "key": "tag",
        "path": "/tag",
        "name": "任务标签管理",
        "catalog": "0",
        "params": []
      }, {
        "key": "taglists",
        "path": "/tag/taglists",
        "name": "标签列表",
        "catalog": "1",
        "params": []
      }
    ]
    return breadcrumbUrl;
  }
}
